name: Generate Datas

on:
  schedule: # execute every 12 hours
    - cron: "* */12 * * *"
  workflow_dispatch: # запуск вручную

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    steps:
      # Создание змейки
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: Levaaaaaa
          svg_out_path: dist/github-contribution-grid-snake.svg

      # Публикация змейки на GitHub Pages
      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
